<?php echo $this->doctype() ?>
<!DOCTYPE html>
<html>

    <head>
    
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        <title>CA Soluções</title>
    
    	<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        	->prependStylesheet($this->basePath('admin/css/estilo.css'))
                        	->prependStylesheet($this->basePath('admin/css/style.min.css'))
                        	->prependStylesheet($this->basePath('css/animate.css'))
                        	->prependStylesheet($this->basePath('css/plugins/chosen/chosen.css'))
    	                    ->prependStylesheet($this->basePath('js/plugins/gritter/jquery.gritter.css'))
                            ->prependStylesheet($this->basePath('css/plugins/toastr/toastr.min.css'))
                            ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
                            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>        
    </head>

    <body>
       
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> 
                        	<span>
                            	<img alt="image" class="img-circle" src="/public/uploads/usuarios/1_avatar.jpg" />
                            </span>
                            
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            	<span class="clear"> 
                            		<span class="block m-t-xs"> 
                            			<strong class="font-bold"><?php echo $this->identity()?></strong>
                            		</span> 
                             		<span class="text-muted text-xs block">Perfil <b class="caret"></b></span> 
                             	</span> 
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="#">Perfil</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('logout')?>">Sair</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    <li <?php if($this->url() == '/admin') echo 'class="active"';?> >
                        <a href="<?php echo $this->url('admin')?>"><i class="fa fa-th-large"></i> <span class="nav-label">Painel</span></a>                        
                    </li>
                    <li <?php if($this->url() == '/admin/materias') echo 'class="active"';?> >
                        <a href="<?php echo $this->url('admin-materias')?>"><i class="fa fa-book" aria-hidden="true"></i> <span class="nav-label">Matérias</span> </a>
                    </li>
                    <li <?php if($this->url() == '/admin/professores') echo 'class="active"';?> >
                        <a href="<?php echo $this->url('admin-professores')?>"><i class="fa fa-flask"></i> <span class="nav-label">Professores</span> </a>
                    </li>
                    <li <?php if($this->url() == '/admin/usuarios') echo 'class="active"';?> >
                        <a href="<?php echo $this->url('admin-usuarios')?>"><i class="fa fa-users" aria-hidden="true"></i> <span class="nav-label">Usuários</span> </a>
                    </li>
                    
                    <li <?php if($this->url() == '/admin/aulas') echo 'class="active"';?> >
                        <a  href="<?php echo $this->url('admin-aulas')?>"><i class="fa fa-star"></i> <span class="nav-label">Aulas</span> <span class="label label-warning pull-right"></span></a>
                    </li>                    
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Busca..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Bem vindo ao SysCA CRM</span>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="mailbox.html">
                                        <div>
                                            <i class="fa fa-envelope fa-fw"></i> 6 Novas solicitações
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="profile.html">
                                        <div>
                                            <i class="fa fa-twitter fa-fw"></i> 2 novos usuários cadastrados                                            
                                        </div>
                                    </a>
                                </li>                                
                            </ul>
                        </li>
        
        
                        <li>
                            <a href="<?php echo $this->url('logout')?>">
                                <i class="fa fa-sign-out"></i> Sair
                            </a>
                        </li>
                    </ul>
        
                </nav>
            </div>
                    
    		<?php  echo $this->content; ?>
            
            <div class="footer">
                <div class="pull-right">
                    
                </div>
                <div>
                    <strong>Copyright</strong> CA Soluções tecnologia &copy; Direitos reservados
                </div>
            </div>
        
        
        </div>
    </div>

	<div class="preloader transparente" id="loader">
        <i class="fa fa-cog fa-spin fa-3x fa-fw i-preloader"></i>			
    </div>


   <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('admin/js/main.js'))
        ->prependFile($this->basePath('admin/js/validador.js'))
        ->prependFile($this->basePath('admin/js/localidades.js'))
        ->prependFile($this->basePath('js/plugins/mascaras/mascaras.js'))
        ->prependFile($this->basePath('js/plugins/mascaras/jquery.mask.min.js'))
        ->prependFile($this->basePath('js/plugins/chosen/chosen.jquery.js'))
        ->prependFile($this->basePath('js/plugins/jquery-ui/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('js/plugins/metisMenu/jquery.metisMenu.js'))
        ->prependFile($this->basePath('js/plugins/jqueryform/jquery.form.min.js'))
        ->prependFile($this->basePath('js/plugins/toastr/toastr.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-2.1.1.js'))
        
        
        
        //-- Flot -->
        /* ->prependFile($this->basePath('js/plugins/flot/jquery.flot.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.tooltip.min.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.spline.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.resize.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.pie.js')) */
        
        //-- Peity -->
        /* ->prependFile($this->basePath('js/plugins/peity/jquery.peity.min.js'))
        ->prependFile($this->basePath('js/demo/peity-demo.js')) */
        
        //-- Custom and plugin javascript -->
        
        //->prependFile($this->basePath('js/plugins/pace/pace.min.js'))
        
        
        //-- GITTER -->
        //->prependFile($this->basePath('js/plugins/gritter/jquery.gritter.min.js'))
        
        //-- Sparkline -->
        //->prependFile($this->basePath('js/plugins/sparkline/jquery.sparkline.min.js'))
        
        //-- Sparkline demo data  -->
        //->prependFile($this->basePath('js/demo/sparkline-demo.js'))
        
        //-- ChartJS-->
        //->prependFile($this->basePath('js/plugins/chartJs/Chart.min.js'))
        
        //-- Toastr -->
        
    ?>     
	</body>
</html>