<?php
$idusuario = $form->get('idusuario');

$nome = $form->get('nome');
$nome->setAttribute('class','form-control');

$cpf = $form->get('cpf');
$cpf->setAttribute('class','form-control cpf');

$rg = $form->get('rg');
$rg->setAttribute('class','form-control inteiro');

$logradouro = $form->get('logradouro');
$logradouro->setAttribute('class','form-control')
           ->setAttribute('id', 'logradouro');

$bairro = $form->get('bairro');
$bairro->setAttribute('class','form-control')
       ->setAttribute('id', 'bairro');

$numero = $form->get('numero');
$numero->setAttribute('class','form-control');

$cep = $form->get('cep');
$cep->setAttribute('class','form-control cep');

$idcidade = $form->get('idcidade');
$idcidade->setAttribute('class','form-control chosen-select')
         ->setAttribute('id', 'idcidade')
         ->setValueOptions(['0' => 'Selecione']);

//add o optin 'selecione' no topo do select
array_unshift($estados, 'Selecione');
$uf = $form->get('uf');
$uf->setAttribute('class','form-control chosen-select uf-select')
   ->setAttribute('data-cid','idcidade')
   ->setAttribute('id', 'uf')
   ->setValueOptions($estados);

$telefone1 = $form->get('telefone1');
$telefone1->setAttribute('class','form-control fone');

$telefone2 = $form->get('telefone2');
$telefone2->setAttribute('class','form-control fone');

$email = $form->get('email');
$email->setAttribute('class','form-control');

$senha = $form->get('senha');
$senha->setAttribute('class','form-control');

$perfil = $form->get('perfil');
$perfil->setAttribute('class','form-control chosen-select');

$observacao = $form->get('observacao');
$observacao->setAttribute('class','form-control');

$dtnascimento = $form->get('dtnascimento');
$dtnascimento->setAttribute('class','form-control data');

$avatar = $form->get('avatar');

$btnsalvar = $form->get('btnsalvar');
$btnsalvar->setAttribute('class','btn btn-primary pull-right');

$btndeletar = $form->get('btndeletar');
$btndeletar->setAttribute('class', 'btn btn-danger pull-right');

$form->setAttribute('action', $this->url('admin-usuarios', ['action'=>'salvar'] ))
     ->setAttribute('class', 'm-t');

$form->prepare();

?>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Usuários</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<?php echo $this->url('admin')?>">Painel</a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('admin-usuarios')?>">Usuários</a>
            </li>
            <li class="active">
                <strong>Cadastro</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <?php echo $this->form()->openTag($form); ?>
              
          <div class="row">
            <div class="col-lg-9">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="row">
                            <div class="form-group col-sm-8">
                                <?php echo $this->formLabel($nome);?>
           						<?php echo $this->formElement($nome);?>           						
           						<span id="nomeHelper" class="help-block"></span>
                            </div>                                
                            <div class="form-group col-sm-4">
                                <?php echo $this->formLabel($perfil);?>
           						<?php echo $this->formElement($perfil);?>           						
           						<span id="perfilHelper" class="help-block"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <?php echo $this->formLabel($cpf);?>
           						<?php echo $this->formElement($cpf);?>           						
           						<span id="cpfHelper" class="help-block"></span>
                            </div>                                
                            <div class="form-group col-sm-3">
                                <?php echo $this->formLabel($rg);?>
           						<?php echo $this->formElement($rg);?>
           						<span id="rgHelper" class="help-block"></span>
                            </div>
                            
                            <div class="clearfix"></div>
                            <div class="hr-line-dashed"></div>
                            
                            <div class="form-group col-sm-3">
                                <?php echo $this->formLabel($cep);?>
           						<?php echo $this->formElement($cep);?>
           						<span id="cepHelper" class="help-block"></span>
                            </div>                            
                            <div class="form-group col-sm-7">
                                <?php echo $this->formLabel($logradouro);?>
           						<?php echo $this->formElement($logradouro);?>
           						<span id="logradouroHelper" class="help-block"></span>
                            </div>                            
                            <div class="form-group col-sm-2">
                                <?php echo $this->formLabel($numero);?>
           						<?php echo $this->formElement($numero);?>           						
                            </div>                            
                            <div class="form-group col-sm-4">
                                <?php echo $this->formLabel($bairro);?>
           						<?php echo $this->formElement($bairro);?>
           						<span id="Helper" class="help-block"></span>
                            </div>
                            
                            <div class="form-group col-sm-3">
                                <?php echo $this->formLabel($uf);?>
           						<?php echo $this->formElement($uf);?>           						
                            </div>
                            
                            <div class="form-group col-sm-5">
                                <?php echo $this->formLabel($idcidade);?>
           						<?php echo $this->formElement($idcidade);?>
           						<span id="idcidadeHelper" class="help-block"></span>
                            </div>
                            
                            <div class="clearfix"></div>
                            <div class="hr-line-dashed"></div>
                            
                            <div class="form-group col-sm-4">
                                <?php echo $this->formLabel($telefone1);?>
           						<?php echo $this->formElement($telefone1);?>
           						<span id="telefone1Helper" class="help-block"></span>
                            </div>
                            
                            <div class="form-group col-sm-4">
                                <?php echo $this->formLabel($telefone2);?>
           						<?php echo $this->formElement($telefone2);?>
           						<span id="telefone2Helper" class="help-block"></span>
                            </div>
                            
                            <div class="form-group col-sm-4">
                                <?php echo $this->formLabel($email);?>
           						<?php echo $this->formElement($email);?>
           						<span id="emailHelper" class="help-block"></span>
                            </div>
                            
                            <div class="form-group col-sm-3">
                                <?php echo $this->formLabel($senha);?>
           						<?php echo $this->formElement($senha);?>
           						<span id="senhaHelper" class="help-block"></span>
                            </div>
                            
                            <div class="form-group col-sm-9">
                                <?php echo $this->formLabel($observacao);?>
           						<?php echo $this->formElement($observacao);?>
                            </div>
                            
                            <div class="clearfix"></div>
                            <div class="col-sm-12">
                            	<?php echo $this->formElement($btnsalvar);?>
                            	<?php echo $this->formElement($btndeletar);?>                            	                            	
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
            </div>
                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Avatar</h5>                            
                        </div>
                        <div class="ibox-content">
                            
                            <?php echo $this->formElement($avatar);?>
                            <span id="avatarHelper" class="help-block"></span>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
              
            <?php echo $this->form()->closeTag();?>            
        </div>
    </div>
</div>

<?php $this->headScript()->prependFile($this->basePath('admin/js/usuarioscadastro.js'))?>