<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Professores</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<?php echo $this->url('admin')?>">Painel</a>
            </li>
            
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
            <a href="#" class="btn btn-primary">Nova aula</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            
        </div>
    </div>
</div>
